# Generated by Django 4.2 on 2023-05-12 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_song_genre_song_likes_song_listening'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 5, 12, 20, 28, 18, 745641)),
        ),
    ]
