# Generated by Django 4.2 on 2023-05-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_song_genre_song_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='listening',
        ),
    ]
