# Generated by Django 4.2 on 2023-05-23 15:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0028_song_like_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='like',
            field=models.ManyToManyField(related_name='like_song', to=settings.AUTH_USER_MODEL),
        ),
    ]
