# Generated by Django 4.2 on 2023-05-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon',
            field=models.ImageField(default='img/profile/icon_user_default.png', upload_to='img/profile/'),
        ),
    ]
